Repository bjarn/jale, pull requests merged in 2020-12, with the labels that each got.

#31 Added Beyondcode Expose support
  README.md
  dist/controllers/installController.js
  dist/controllers/installController.js.map
  dist/tools/expose.js
  dist/tools/expose.js.map
  dist/tools/tool.js
  dist/tools/tool.js.map
  dist/utils/tools.js
  dist/utils/tools.js.map
  src/controllers/installController.ts
  src/tools/expose.ts
  src/tools/tool.ts
  src/utils/tools.ts
Labels: feature

#34 Renamed 'domain' to 'tld' in Jale config
  dist/controllers/installController.js
  dist/controllers/installController.js.map
  dist/controllers/secureController.js
  dist/controllers/secureController.js.map
  dist/controllers/sitesController.js
  dist/controllers/sitesController.js.map
  dist/controllers/subdomainController.js
  dist/controllers/subdomainController.js.map
  dist/services/dnsmasq.js
  dist/services/dnsmasq.js.map
  dist/services/elasticsearch.js
  dist/services/elasticsearch.js.map
  dist/services/mailhog.js
  dist/services/mailhog.js.map
  dist/templates/nginx/elasticsearch.js
  dist/templates/nginx/elasticsearch.js.map
  dist/templates/nginx/mailhog.js
  dist/templates/nginx/mailhog.js.map
  src/controllers/installController.ts
  src/controllers/secureController.ts
  src/controllers/sitesController.ts
  src/controllers/subdomainController.ts
  src/models/config.ts
  src/services/dnsmasq.ts
  src/services/elasticsearch.ts
  src/services/mailhog.ts
  src/templates/nginx/elasticsearch.ts
  src/templates/nginx/mailhog.ts
Labels: patch

#36 Added unlink command
  dist/commands/unlinkCommand.js
  dist/commands/unlinkCommand.js.map
  dist/controllers/sitesController.js
  dist/controllers/sitesController.js.map
  dist/utils/console.js
  dist/utils/console.js.map
  src/commands/unlinkCommand.ts
  src/controllers/sitesController.ts
  src/utils/console.ts
Labels: feature

#42 Fixed installer incorrectly configuring DnsMasq
  dist/controllers/serviceController.js
  dist/controllers/serviceController.js.map
  dist/services/dnsmasq.js
  dist/services/dnsmasq.js.map
  src/controllers/serviceController.ts
  src/services/dnsmasq.ts
Labels: bug, patch

#43 Change jale config path to ~/.config/jale
  dist/utils/jale.js
  dist/utils/jale.js.map
  src/utils/jale.ts
Labels: enhancement

#44 Fix PHP 8.0 always installing when switching PHP versions
  dist/services/phpFpm80.js
  dist/services/phpFpm80.js.map
  dist/utils/phpFpm.js
  dist/utils/phpFpm.js.map
  src/services/phpFpm80.ts
  src/utils/phpFpm.ts
Labels: bugfix, patch

#46 Revert directory change from v0.4.1
  dist/utils/jale.js
  dist/utils/jale.js.map
  src/utils/jale.ts
Labels: enhancement, patch

#47 Add a command to list the nginx vhost configurations currently active
  dist/commands/linksCommand.js
  dist/commands/linksCommand.js.map
  dist/controllers/secureController.js
  dist/controllers/secureController.js.map
  dist/controllers/sitesController.js
  dist/controllers/sitesController.js.map
  package-lock.json
  package.json
  src/commands/linksCommand.ts
  src/controllers/secureController.ts
  src/controllers/sitesController.ts
Labels: feature, minor
